---
application:
  name: "status-labibweb"
  project: "status-labibweb"
  organization: "QoveryCommunity"
routers:
- name: "main-status-labibweb"
  routes:
  - application_name: "status-labibweb"
    paths:
    - "/*"
